theme: jekyll-theme-minimal
title: Agent-Based Modeling for Archaeology
description: When warm weather comes, researchers from around the world gather in Santa Fe for an unusual kind of summer school. For four weeks, experts from disciplines ranging from anthropology to quantum mechanics learn the essentials of complexity science. Along the way, they learn to think and work in new ways and make life-long connections with other researchers. 
logo: https://slack-imgs.com/?c=1&o1=ro&url=https%3A%2F%2Fs3.amazonaws.com%2Fsfi-edu%2Fsfi-edu%2Fproduction%2Fstatic%2Fsfi-share-default.jpg
 
