theme: jekyll-theme-minimal
title: Agent-Based Modeling for Archaeology
description: 
<details>
  <summary>Chapter One</summary>
  
  Putting regular text here to see how it renders.
  ``
  1.1
  1.2
  1.3
  1.4 [practice](https://www.npr.org/)
  ``
</details>
logo: https://slack-imgs.com/?c=1&o1=ro&url=https%3A%2F%2Fs3.amazonaws.com%2Fsfi-edu%2Fsfi-edu%2Fproduction%2Fstatic%2Fsfi-share-default.jpg

 
