theme: jekyll-theme-minimal
title: Agent-Based Modeling for Archaeology
logo: https://images.squarespace-cdn.com/content/v1/5d420e5d999d0200013d33c3/1623350954427-ODDFXU5RIFW0PEPNY5NO/ke17ZwdGBToddI8pDm48kL_Uk9XwACdsdIGnLLdDW8hZw-zPPgdn4jUwVcJE1ZvWQUxwkmyExglNqGp0IvTJZUJFbgE-7XRK3dMEBRBhUpyUDcMq-LO-ZJMuIa2SeqaUG_laECe3ULYF42DwVThV6XlHeZwUcWC0fBVux1QdRpk/1TOC+New+Imam+River+42B.png?format=2500w
show_downloads: false
description: Table of Contents
description: Chapter 1
description: Chapter 2
description: Chapter 3
description: Chapter 4
description: Chapter 5
description: Chapter 6
description: Chapter 7
description: Chapter 8
description: Chapter 9
description: Conclusion 
description: Appendix

description: Entire Book (PDF)

description: Resources
description: Bibliography
description: About the Authors
description: To Order Book
