theme: jekyll-theme-minimal
title: Agent-Based Modeling for Archaeology
logo: https://images.squarespace-cdn.com/content/v1/5d420e5d999d0200013d33c3/1623354016095-NT2EFWWCNU4Y7QNT28ZQ/ke17ZwdGBToddI8pDm48kL_Uk9XwACdsdIGnLLdDW8hZw-zPPgdn4jUwVcJE1ZvWQUxwkmyExglNqGp0IvTJZUJFbgE-7XRK3dMEBRBhUpyUDcMq-LO-ZJMuIa2SeqaUG_laECe3ULYF42DwVThV6XlHeZwUcWC0fBVux1QdRpk/6Chapter5_Galata-Istanbul.png?format=2500w
show_downloads: false
description: To Order Book
